import React, { createContext, useContext, useEffect, useState, useCallback } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.search": "Search",
    "nav.about": "About Us",
    "nav.contact": "Contact Us",
    "nav.profile": "Profile",
    "nav.appointments": "Appointments",
    "nav.chats": "Chats",
    "nav.alerts": "Alerts",
    "nav.settings": "Settings",
    "nav.admin": "Admin Portal",
    "nav.signIn": "Sign In",
    "nav.signOut": "Sign Out",

    // Home
    "home.hero.title1": "Find the Right",
    "home.hero.title2": "Professional",
    "home.hero.title3": "for Every Need",
    "home.hero.desc": "SaySerné connects you with top-rated, verified professionals across every industry. Browse anonymously, book with confidence.",
    "home.findProfessionals": "Find Professionals",
    "home.joinAsProfessional": "Join as Professional",
    "home.topRated": "Top Rated Professionals",
    "home.topRatedDesc": "Highest rated professionals on the platform",
    "home.viewAll": "View All",
    "home.noProfessionals": "No professionals listed yet. Be the first to join!",
    "home.browseByCategory": "Browse by Category",
    "home.exploreCats": "Explore services across all industries",
    "home.whySayserne": "Why SaySerné?",
    "home.verifiedReviews": "Verified Reviews",
    "home.verifiedReviewsDesc": "Only clients with completed bookings can leave reviews",
    "home.advancedSearch": "Advanced Search",
    "home.advancedSearchDesc": "Filter by category, rating, cost, experience, and more",
    "home.easyBooking": "Easy Booking",
    "home.easyBookingDesc": "Request appointments with approval workflow",
    "home.realtimeChat": "Real-time Chat",
    "home.realtimeChatDesc": "Communicate directly with professionals",
    "home.readyToStart": "Ready to Get Started?",
    "home.readyToStartDesc": "Join thousands of professionals and clients on SaySerné. Create your profile today.",
    "home.browseProfessionals": "Browse Professionals",
    "home.createAccount": "Create Account",

    // Search
    "search.title": "Find Professionals",
    "search.firstName": "First name...",
    "search.lastName": "Last name...",
    "search.filters": "Filters",
    "search.advancedFilters": "Advanced Filters",
    "search.clearAll": "Clear All",
    "search.category": "Category",
    "search.service": "Service",
    "search.gender": "Gender",
    "search.nationality": "Nationality",
    "search.country": "Country",
    "search.city": "City",
    "search.minStars": "Min Stars",
    "search.minCost": "Min Cost/hr",
    "search.maxCost": "Max Cost/hr",
    "search.minExperience": "Min Experience (yrs)",
    "search.hasTeam": "Has Team",
    "search.hasOffice": "Has Office",
    "search.sortBy": "Sort By",
    "search.order": "Order",
    "search.allCategories": "All Categories",
    "search.allServices": "All Services",
    "search.any": "Any",
    "search.male": "Male",
    "search.female": "Female",
    "search.rating": "Rating",
    "search.cost": "Cost",
    "search.experience": "Experience",
    "search.age": "Age",
    "search.descending": "Descending",
    "search.ascending": "Ascending",
    "search.professionalsFound": "{count} professional{s} found",
    "search.searching": "Searching...",
    "search.noResults": "No professionals match your criteria",
    "search.clearFilters": "Clear Filters",
    "search.previous": "Previous",
    "search.next": "Next",
    "search.page": "Page {current} of {total}",
    "search.allCountries": "All Countries",
    "search.allCities": "All Cities",

    // About
    "about.title": "About SaySerné",
    "about.desc": "SaySerné is a next-generation professional services marketplace built on trust, transparency, and an omnichannel approach to connecting clients with the right professionals.",
    "about.mission": "Our Mission",
    "about.missionP1": "We believe that finding the right professional should be simple, transparent, and trustworthy. SaySerné was created to bridge the gap between clients seeking quality services and professionals looking to grow their practice.",
    "about.missionP2": "Our platform uses a meritocratic ranking system where professionals earn their reputation through verified client reviews, ensuring that quality always rises to the top.",
    "about.values": "Our Values",
    "about.trust": "Trust & Transparency",
    "about.trustDesc": "Every review is verified through completed bookings",
    "about.meritocracy": "Meritocracy",
    "about.meritocracyDesc": "Rankings based on real performance, not paid placement alone",
    "about.omnichannel": "Omnichannel Access",
    "about.omnichannelDesc": "Seamless experience across web, mobile, and all touchpoints",
    "about.community": "Community First",
    "about.communityDesc": "Building meaningful connections between professionals and clients",
    "about.howItWorks": "How It Works",
    "about.step1Title": "Browse & Search",
    "about.step1Desc": "Explore professionals by category, service, rating, and more. No account needed to browse.",
    "about.step2Title": "Book & Connect",
    "about.step2Desc": "Create an account, request appointments, and chat directly with professionals.",
    "about.step3Title": "Review & Rate",
    "about.step3Desc": "After a completed booking, share your experience to help the community.",

    // Contact
    "contact.title": "Contact Us",
    "contact.desc": "Have a question or feedback? We'd love to hear from you.",
    "contact.email": "Email Address",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sent": "Message Sent!",
    "contact.sentDesc": "We'll get back to you as soon as possible.",
    "contact.sendAnother": "Send Another Message",

    // Profile
    "profile.title": "My Profile",
    "profile.personalInfo": "Personal Info",
    "profile.myServices": "My Services",
    "profile.availability": "Availability",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.phone": "Phone",
    "profile.gender": "Gender",
    "profile.preferNotToSay": "Prefer not to say",
    "profile.dateOfBirth": "Date of Birth",
    "profile.nationality": "Nationality",
    "profile.country": "Country",
    "profile.bio": "Bio",
    "profile.save": "Save Changes",
    "profile.saving": "Saving...",
    "profile.addService": "Add Service",
    "profile.servicesListed": "{count} service(s) listed",
    "profile.noServices": "No services listed yet. Add your first service to start receiving bookings.",
    "profile.selectCategory": "Select Category",
    "profile.selectService": "Select Service",
    "profile.costPerHour": "Cost/Hour ($)",
    "profile.yearsExp": "Years of Experience",
    "profile.website": "Website",
    "profile.serviceCountry": "Country",
    "profile.serviceCity": "City",
    "profile.hasTeam": "Has Team",
    "profile.teamSize": "Team Size",
    "profile.hasOffice": "Has Office",
    "profile.officeAddress": "Office Address",
    "profile.officeCity": "Office City",
    "profile.officeCountry": "Office Country",
    "profile.geographicAreas": "Geographic Areas (comma separated)",
    "profile.adding": "Adding...",
    "profile.setAvailability": "Set your weekly availability",
    "profile.addSlot": "Add Slot",
    "profile.noSlots": "No availability slots. Add your working hours.",
    "profile.saveAvailability": "Save Availability",

    // Professional Profile
    "profProfile.backToSearch": "Back to Search",
    "profProfile.bookAppointment": "Book Appointment",
    "profProfile.chat": "Chat",
    "profProfile.services": "Services",
    "profProfile.reviews": "Reviews",
    "profProfile.availability": "Availability",
    "profProfile.noServices": "No services listed yet",
    "profProfile.noReviews": "No reviews yet",
    "profProfile.noAvailability": "No availability set",
    "profProfile.notFound": "Professional not found",
    "profProfile.perHour": "/hr",
    "profProfile.years": "years",
    "profProfile.teamOf": "Team of",
    "profProfile.office": "Office",

    // Appointments
    "appointments.title": "My Appointments",
    "appointments.noAppointments": "No appointments yet",
    "appointments.approve": "Approve",
    "appointments.decline": "Decline",
    "appointments.cancel": "Cancel",
    "appointments.complete": "Complete",
    "appointments.pending": "Pending",
    "appointments.approved": "Approved",
    "appointments.cancelled": "Cancelled",
    "appointments.completed": "Completed",
    "appointments.asClient": "As Client",
    "appointments.asProfessional": "As Professional",
    "appointments.statusUpdated": "Status updated!",
    "appointments.review": "Review",
    "appointments.leaveReview": "Leave a Review",
    "appointments.ratingLabel": "Rating",
    "appointments.commentLabel": "Comment (optional)",
    "appointments.commentPlaceholder": "Share your experience...",
    "appointments.submitReview": "Submit Review",
    "appointments.submitting": "Submitting...",
    "appointments.reviewSubmitted": "Review submitted!",

    // Chats
    "chats.title": "Messages",
    "chats.noChats": "No conversations yet",
    "chats.startFromProfile": "Start a chat from a professional's profile",
    "chats.selectChat": "Select a conversation to start chatting",
    "chats.typeMessage": "Type a message...",
    "chats.conversation": "Conversation",
    "chats.noMessages": "No messages yet. Say hello!",

    // Alerts
    "alerts.title": "My Alerts",
    "alerts.create": "Create Alert",
    "alerts.createAlert": "Create Search Alert",
    "alerts.noAlerts": "No alerts set up yet. Create one to get notified about new professionals.",
    "alerts.name": "Alert Name",
    "alerts.namePlaceholder": "e.g. Top Plumbers",
    "alerts.enterName": "Please enter a name",
    "alerts.frequency": "Frequency",
    "alerts.daily": "Daily",
    "alerts.weekly": "Weekly",
    "alerts.monthly": "Monthly",
    "alerts.run": "Run",
    "alerts.delete": "Delete",
    "alerts.created": "Alert created!",
    "alerts.deleted": "Alert deleted",
    "alerts.creating": "Creating...",

    // Settings
    "settings.title": "Settings",
    "settings.theme": "Appearance",
    "settings.themeDesc": "Switch between day and night themes",
    "settings.language": "Language",
    "settings.languageDesc": "Choose your preferred language",
    "settings.lightMode": "Light Mode",
    "settings.darkMode": "Dark Mode",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Manage your notification preferences",
    "settings.appointmentReminders": "Appointment Reminders",
    "settings.appointmentRemindersDesc": "Get notified before upcoming appointments",
    "settings.newMessages": "New Messages",
    "settings.newMessagesDesc": "Notifications for new chat messages",
    "settings.alertMatches": "Alert Matches",
    "settings.alertMatchesDesc": "When new professionals match your saved alerts",
    "settings.reviewNotifs": "Review Notifications",
    "settings.reviewNotifsDesc": "When someone reviews your service",
    "settings.account": "Account",
    "settings.name": "Name",
    "settings.email": "Email",
    "settings.role": "Role",
    "settings.notSet": "Not set",

    // Admin
    "admin.title": "Back Office",
    "admin.dashboard": "Dashboard",
    "admin.users": "Users",
    "admin.ads": "Advertisements",
    "admin.contacts": "Contact Messages",
    "admin.totalUsers": "Total Users",
    "admin.professionals": "Professionals",
    "admin.totalBookings": "Total Bookings",
    "admin.totalReviews": "Total Reviews",
    "admin.accessDenied": "Access Denied: Admin privileges required",
    "admin.updated": "Updated",
    "admin.user": "User",
    "admin.emailCol": "Email",
    "admin.roleCol": "Role",
    "admin.statusCol": "Status",
    "admin.actionsCol": "Actions",
    "admin.locked": "Locked",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.pageLabel": "Page",
    "admin.adsCount": "advertisement(s)",
    "admin.newAd": "New Ad",
    "admin.createAd": "Create Advertisement",
    "admin.adTitle": "Title",
    "admin.adImageUrl": "Image URL",
    "admin.adLinkUrl": "Link URL (optional)",
    "admin.adPosition": "Position",
    "admin.homeBanner": "Home Banner",
    "admin.searchBanner": "Search Banner",
    "admin.sidebar": "Sidebar",
    "admin.creating": "Creating...",
    "admin.adCreated": "Ad created!",
    "admin.adDeleted": "Ad deleted",
    "admin.noAds": "No advertisements yet",
    "admin.noContacts": "No contact messages yet",

    // Book Appointment
    "book.title": "Book Appointment",
    "book.with": "with",
    "book.service": "Service",
    "book.selectService": "Select a service",
    "book.generalAppointment": "General Appointment",
    "book.date": "Date",
    "book.time": "Time",
    "book.description": "Description (optional)",
    "book.descriptionPlaceholder": "Describe what you need...",
    "book.requestAppointment": "Request Appointment",
    "book.requesting": "Requesting...",
    "book.requested": "Appointment requested!",
    "book.requestedTitle": "Appointment Requested!",
    "book.requestedDesc": "The professional will review your request and respond soon.",
    "book.viewAppointments": "View My Appointments",
    "book.backToProfile": "Back to Profile",
    "book.selectDateTime": "Please select date and time",
    "book.back": "Back",

    // Footer
    "footer.desc": "Connecting clients with top-rated professionals through a seamless omnichannel experience.",
    "footer.platform": "Platform",
    "footer.findProfessionals": "Find Professionals",
    "footer.aboutUs": "About Us",
    "footer.contactUs": "Contact Us",
    "footer.forProfessionals": "For Professionals",
    "footer.createProfile": "Create Profile",
    "footer.manageBookings": "Manage Bookings",
    "footer.support": "Support",
    "footer.helpCenter": "Help Center",
    "footer.terms": "Terms of Service",
    "footer.rights": "All rights reserved.",

    // Common
    "common.premium": "Premium",
    "common.starred": "Starred",
    "common.team": "Team",
    "common.loading": "Loading...",
    "common.to": "to",

    // Profile extras
    "profile.saved": "Profile updated!",
    "profile.saveChanges": "Save Changes",
    "profile.serviceAdded": "Service added!",
    "profile.serviceRemoved": "Service removed",
    "profile.selectCatAndService": "Select category and service",
    "profile.countryRequired": "Country is required for each service",
    "profile.countryPlaceholder": "e.g. Lebanon",
    "profile.cityPlaceholder": "e.g. Beirut",
    "profile.workLocation": "Work Location",
    "profile.city": "City",
    "profile.category": "Category",
    "profile.service": "Service",
    "profile.yearsOfExperience": "Years of Experience",
    "profile.noLocation": "No location set",
    "profile.noServicesYet": "No services listed yet. Add your first service to start receiving bookings.",
    "profile.to": "to",
    "profile.availabilitySaved": "Availability saved!",
    "profile.select": "Select",

    // About extras
    "about.subtitle": "SaySerné is a next-generation professional services marketplace built on trust, transparency, and an omnichannel approach.",
    "about.step1": "Browse & Search",
    "about.step2": "Book & Connect",
    "about.step3": "Review & Rate",

    // Contact extras
    "contact.subtitle": "Have a question or feedback? We'd love to hear from you.",
    "contact.sentTitle": "Message Sent!",
    "contact.fillAll": "Please fill in all fields",
    "contact.subjectPlaceholder": "What is this about?",
    "contact.messagePlaceholder": "Tell us more...",

    // ProfProfile extras
    "profProfile.chatStarted": "Chat started! Go to your Chats to continue.",

    // Chat media
    "chats.sendImage": "Send Image",
    "chats.sendVideo": "Send Video",
    "chats.sendLocation": "Share Location",
    "chats.shareLocation": "Share Location",
    "chats.shareCurrentLocation": "Share Current Location",
    "chats.or": "or enter manually",
    "chats.locationDescription": "Location Description",
    "chats.locationPlaceholder": "e.g. My office at Downtown",
    "chats.googleMapsLink": "Google Maps Link",
    "chats.optional": "optional",
    "chats.send": "Send",
    "chats.location": "Location",
    "chats.viewOnMap": "View on Map",
    "chats.fileTooLarge": "File is too large. Max 5MB for images, 10MB for videos.",
    "chats.uploading": "Uploading...",
    "chats.locationDenied": "Location access denied",
    "chats.locationNotSupported": "Geolocation not supported",

    // Booking overlap
    "book.selectServiceRequired": "Please select a service",
    "book.duration": "Duration",
    "book.minutes": "minutes",
    "book.hour": "hour",
    "book.hours": "hours",
    "book.existingAppointments": "Existing appointments on this date",
    "book.overlapWarning": "Time slot conflict detected!",
    "book.overlapDesc": "Your selected time overlaps with an existing appointment. You may still submit, but approval is unlikely.",
    "book.noServicesAvailable": "No services available for booking",

    // Reviews
    "appointments.reviewed": "Reviewed",

    // Admin extras
    "admin.categories": "Categories",
    "admin.services": "Services",
    "admin.aboutUs": "About Us",
    "admin.chatMonitor": "Chat Monitor",
    "admin.fees": "Professional Fees",
    "admin.createUser": "Create User",
    "admin.viewDetails": "View Details",
    "admin.lock": "Lock",
    "admin.unlock": "Unlock",
    "admin.makeAdmin": "Make Admin",
    "admin.removeAdmin": "Remove Admin",
    "admin.blocked": "Blocked",
    "admin.unblocked": "Unblocked",
    "admin.block": "Block",
    "admin.unblock": "Unblock",
    "admin.respond": "Respond",
    "admin.reply": "Reply",
    "admin.pending": "Pending",
    "admin.inProgress": "In Progress",
    "admin.closed": "Closed",
    "admin.allStatuses": "All Statuses",
    "admin.save": "Save",
    "admin.saving": "Saving...",
    "admin.saved": "Saved!",
    "admin.delete": "Delete",
    "admin.edit": "Edit",
    "admin.add": "Add",
    "admin.name": "Name",
    "admin.nameAr": "Name (Arabic)",
    "admin.description": "Description",
    "admin.descriptionAr": "Description (Arabic)",
    "admin.status": "Status",
    "admin.fee": "Fee",
    "admin.feeAmount": "Fee Amount ($)",
    "admin.feeEnabled": "Fee Enabled",
    "admin.noFees": "No professional fees configured",
    "admin.userCreated": "User created!",
    "admin.userUpdated": "User updated!",
    "admin.contactReplied": "Reply sent!",
    "admin.statusChanged": "Status changed!",

    // Profile type
    "profile.profileType": "Profile Type",
    "profile.customer": "Customer",
    "profile.professional": "Professional",
    "profile.profileTypeDesc": "Switch to Professional to manage services and availability",

    // Home extra badges/stats
    "home.hero.badge": "Professional Services Marketplace",
    "home.stat.countries": "Countries",
    "home.stat.professionals": "Professionals",
    "home.stat.satisfaction": "Satisfaction",
    "home.topRatedBadge": "TOP RATED",
    "home.categoriesBadge": "EXPLORE",

    // Missing keys - About
    "about.badge": "ABOUT US",

    // Missing keys - Contact info cards
    "contact.chatTitle": "Get in Touch",
    "contact.chatDesc": "We're here to help with any questions about our platform.",
    "contact.responseTitle": "Quick Response",
    "contact.responseDesc": "We typically respond within 24 hours.",
    "contact.secureTitle": "Secure & Private",
    "contact.secureDesc": "Your information is kept confidential and secure.",
    "contact.loggedInAs": "Sending as",

    // Missing keys - Search
    "search.subtitle": "Discover top professionals near you",
  },
  ar: {
    // Navbar
    "nav.home": "الرئيسية",
    "nav.search": "بحث",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.profile": "الملف الشخصي",
    "nav.appointments": "المواعيد",
    "nav.chats": "المحادثات",
    "nav.alerts": "التنبيهات",
    "nav.settings": "الإعدادات",
    "nav.admin": "لوحة الإدارة",
    "nav.signIn": "تسجيل الدخول",
    "nav.signOut": "تسجيل الخروج",

    // Home
    "home.hero.title1": "ابحث عن",
    "home.hero.title2": "المحترف المناسب",
    "home.hero.title3": "لكل احتياجاتك",
    "home.hero.desc": "SaySerné يربطك بأفضل المحترفين المعتمدين في كل مجال. تصفح بحرية، واحجز بثقة.",
    "home.findProfessionals": "ابحث عن محترفين",
    "home.joinAsProfessional": "انضم كمحترف",
    "home.topRated": "أفضل المحترفين تقييماً",
    "home.topRatedDesc": "أعلى المحترفين تقييماً على المنصة",
    "home.viewAll": "عرض الكل",
    "home.noProfessionals": "لا يوجد محترفون مسجلون بعد. كن أول من ينضم!",
    "home.browseByCategory": "تصفح حسب الفئة",
    "home.exploreCats": "استكشف الخدمات في جميع المجالات",
    "home.whySayserne": "لماذا SaySerné؟",
    "home.verifiedReviews": "تقييمات موثقة",
    "home.verifiedReviewsDesc": "فقط العملاء الذين أتموا حجزاً يمكنهم ترك تقييم",
    "home.advancedSearch": "بحث متقدم",
    "home.advancedSearchDesc": "فلتر حسب الفئة والتقييم والتكلفة والخبرة والمزيد",
    "home.easyBooking": "حجز سهل",
    "home.easyBookingDesc": "اطلب مواعيد مع نظام موافقة",
    "home.realtimeChat": "محادثة فورية",
    "home.realtimeChatDesc": "تواصل مباشرة مع المحترفين",
    "home.readyToStart": "مستعد للبدء؟",
    "home.readyToStartDesc": "انضم إلى آلاف المحترفين والعملاء على SaySerné. أنشئ ملفك الشخصي اليوم.",
    "home.browseProfessionals": "تصفح المحترفين",
    "home.createAccount": "إنشاء حساب",

    // Search
    "search.title": "ابحث عن محترفين",
    "search.firstName": "الاسم الأول...",
    "search.lastName": "اسم العائلة...",
    "search.filters": "الفلاتر",
    "search.advancedFilters": "فلاتر متقدمة",
    "search.clearAll": "مسح الكل",
    "search.category": "الفئة",
    "search.service": "الخدمة",
    "search.gender": "الجنس",
    "search.nationality": "الجنسية",
    "search.country": "البلد",
    "search.city": "المدينة",
    "search.minStars": "الحد الأدنى للنجوم",
    "search.minCost": "الحد الأدنى للتكلفة/ساعة",
    "search.maxCost": "الحد الأقصى للتكلفة/ساعة",
    "search.minExperience": "الحد الأدنى للخبرة (سنوات)",
    "search.hasTeam": "لديه فريق",
    "search.hasOffice": "لديه مكتب",
    "search.sortBy": "ترتيب حسب",
    "search.order": "الترتيب",
    "search.allCategories": "جميع الفئات",
    "search.allServices": "جميع الخدمات",
    "search.any": "الكل",
    "search.male": "ذكر",
    "search.female": "أنثى",
    "search.rating": "التقييم",
    "search.cost": "التكلفة",
    "search.experience": "الخبرة",
    "search.age": "العمر",
    "search.descending": "تنازلي",
    "search.ascending": "تصاعدي",
    "search.professionalsFound": "{count} محترف تم العثور عليه",
    "search.searching": "جاري البحث...",
    "search.noResults": "لا يوجد محترفون يطابقون معاييرك",
    "search.clearFilters": "مسح الفلاتر",
    "search.previous": "السابق",
    "search.next": "التالي",
    "search.page": "صفحة {current} من {total}",
    "search.allCountries": "جميع البلدان",
    "search.allCities": "جميع المدن",

    // About
    "about.title": "عن SaySerné",
    "about.desc": "SaySerné هو سوق خدمات مهنية من الجيل القادم مبني على الثقة والشفافية ونهج متعدد القنوات لربط العملاء بالمحترفين المناسبين.",
    "about.mission": "مهمتنا",
    "about.missionP1": "نؤمن بأن إيجاد المحترف المناسب يجب أن يكون بسيطاً وشفافاً وموثوقاً. تم إنشاء SaySerné لسد الفجوة بين العملاء الباحثين عن خدمات عالية الجودة والمحترفين الذين يتطلعون لتنمية ممارساتهم.",
    "about.missionP2": "تستخدم منصتنا نظام تصنيف جدارة حيث يكسب المحترفون سمعتهم من خلال تقييمات العملاء الموثقة.",
    "about.values": "قيمنا",
    "about.trust": "الثقة والشفافية",
    "about.trustDesc": "كل تقييم موثق من خلال حجوزات مكتملة",
    "about.meritocracy": "الجدارة",
    "about.meritocracyDesc": "التصنيفات مبنية على الأداء الحقيقي",
    "about.omnichannel": "وصول متعدد القنوات",
    "about.omnichannelDesc": "تجربة سلسة عبر الويب والجوال وجميع نقاط الاتصال",
    "about.community": "المجتمع أولاً",
    "about.communityDesc": "بناء روابط ذات معنى بين المحترفين والعملاء",
    "about.howItWorks": "كيف يعمل",
    "about.step1Title": "تصفح وابحث",
    "about.step1Desc": "استكشف المحترفين حسب الفئة والخدمة والتقييم والمزيد. لا حاجة لحساب للتصفح.",
    "about.step2Title": "احجز وتواصل",
    "about.step2Desc": "أنشئ حساباً، اطلب مواعيد، وتحدث مباشرة مع المحترفين.",
    "about.step3Title": "قيّم وراجع",
    "about.step3Desc": "بعد إتمام الحجز، شارك تجربتك لمساعدة المجتمع.",

    // Contact
    "contact.title": "اتصل بنا",
    "contact.desc": "لديك سؤال أو ملاحظة؟ يسعدنا سماعك.",
    "contact.email": "البريد الإلكتروني",
    "contact.subject": "الموضوع",
    "contact.message": "الرسالة",
    "contact.send": "إرسال الرسالة",
    "contact.sending": "جاري الإرسال...",
    "contact.sent": "تم إرسال الرسالة!",
    "contact.sentDesc": "سنعود إليك في أقرب وقت ممكن.",
    "contact.sendAnother": "إرسال رسالة أخرى",

    // Profile
    "profile.title": "ملفي الشخصي",
    "profile.personalInfo": "المعلومات الشخصية",
    "profile.myServices": "خدماتي",
    "profile.availability": "التوفر",
    "profile.firstName": "الاسم الأول",
    "profile.lastName": "اسم العائلة",
    "profile.phone": "الهاتف",
    "profile.gender": "الجنس",
    "profile.preferNotToSay": "أفضل عدم الإفصاح",
    "profile.dateOfBirth": "تاريخ الميلاد",
    "profile.nationality": "الجنسية",
    "profile.country": "البلد",
    "profile.bio": "نبذة",
    "profile.save": "حفظ التغييرات",
    "profile.saving": "جاري الحفظ...",
    "profile.addService": "إضافة خدمة",
    "profile.servicesListed": "{count} خدمة مسجلة",
    "profile.noServices": "لا توجد خدمات مسجلة بعد. أضف خدمتك الأولى لبدء تلقي الحجوزات.",
    "profile.selectCategory": "اختر الفئة",
    "profile.selectService": "اختر الخدمة",
    "profile.costPerHour": "التكلفة/ساعة ($)",
    "profile.yearsExp": "سنوات الخبرة",
    "profile.website": "الموقع الإلكتروني",
    "profile.serviceCountry": "البلد",
    "profile.serviceCity": "المدينة",
    "profile.hasTeam": "لديه فريق",
    "profile.teamSize": "حجم الفريق",
    "profile.hasOffice": "لديه مكتب",
    "profile.officeAddress": "عنوان المكتب",
    "profile.officeCity": "مدينة المكتب",
    "profile.officeCountry": "بلد المكتب",
    "profile.geographicAreas": "المناطق الجغرافية (مفصولة بفواصل)",
    "profile.adding": "جاري الإضافة...",
    "profile.setAvailability": "حدد أوقات توفرك الأسبوعية",
    "profile.addSlot": "إضافة فترة",
    "profile.noSlots": "لا توجد فترات توفر. أضف ساعات عملك.",
    "profile.saveAvailability": "حفظ التوفر",

    // Professional Profile
    "profProfile.backToSearch": "العودة للبحث",
    "profProfile.bookAppointment": "حجز موعد",
    "profProfile.chat": "محادثة",
    "profProfile.services": "الخدمات",
    "profProfile.reviews": "التقييمات",
    "profProfile.availability": "التوفر",
    "profProfile.noServices": "لا توجد خدمات مسجلة بعد",
    "profProfile.noReviews": "لا توجد تقييمات بعد",
    "profProfile.noAvailability": "لم يتم تحديد التوفر",
    "profProfile.notFound": "لم يتم العثور على المحترف",
    "profProfile.perHour": "/ساعة",
    "profProfile.years": "سنوات",
    "profProfile.teamOf": "فريق من",
    "profProfile.office": "مكتب",

    // Appointments
    "appointments.title": "مواعيدي",
    "appointments.noAppointments": "لا توجد مواعيد بعد",
    "appointments.approve": "موافقة",
    "appointments.decline": "رفض",
    "appointments.cancel": "إلغاء",
    "appointments.complete": "إكمال",
    "appointments.pending": "قيد الانتظار",
    "appointments.approved": "تمت الموافقة",
    "appointments.cancelled": "ملغي",
    "appointments.completed": "مكتمل",
    "appointments.asClient": "كعميل",
    "appointments.asProfessional": "كمحترف",
    "appointments.statusUpdated": "تم تحديث الحالة!",
    "appointments.review": "تقييم",
    "appointments.leaveReview": "اترك تقييماً",
    "appointments.ratingLabel": "التقييم",
    "appointments.commentLabel": "تعليق (اختياري)",
    "appointments.commentPlaceholder": "شارك تجربتك...",
    "appointments.submitReview": "إرسال التقييم",
    "appointments.submitting": "جاري الإرسال...",
    "appointments.reviewSubmitted": "تم إرسال التقييم!",

    // Chats
    "chats.title": "الرسائل",
    "chats.noChats": "لا توجد محادثات بعد",
    "chats.startFromProfile": "ابدأ محادثة من ملف محترف",
    "chats.selectChat": "اختر محادثة للبدء",
    "chats.typeMessage": "اكتب رسالة...",
    "chats.conversation": "محادثة",
    "chats.noMessages": "لا توجد رسائل بعد. قل مرحباً!",

    // Alerts
    "alerts.title": "تنبيهاتي",
    "alerts.create": "إنشاء تنبيه",
    "alerts.createAlert": "إنشاء تنبيه بحث",
    "alerts.noAlerts": "لا توجد تنبيهات بعد. أنشئ واحداً ليتم إعلامك عن محترفين جدد.",
    "alerts.name": "اسم التنبيه",
    "alerts.namePlaceholder": "مثال: أفضل السباكين",
    "alerts.enterName": "يرجى إدخال اسم",
    "alerts.frequency": "التكرار",
    "alerts.daily": "يومي",
    "alerts.weekly": "أسبوعي",
    "alerts.monthly": "شهري",
    "alerts.run": "تشغيل",
    "alerts.delete": "حذف",
    "alerts.created": "تم إنشاء التنبيه!",
    "alerts.deleted": "تم حذف التنبيه",
    "alerts.creating": "جاري الإنشاء...",

    // Settings
    "settings.title": "الإعدادات",
    "settings.theme": "المظهر",
    "settings.themeDesc": "التبديل بين الوضع النهاري والليلي",
    "settings.language": "اللغة",
    "settings.languageDesc": "اختر لغتك المفضلة",
    "settings.lightMode": "الوضع النهاري",
    "settings.darkMode": "الوضع الليلي",
    "settings.notifications": "الإشعارات",
    "settings.notificationsDesc": "إدارة تفضيلات الإشعارات",
    "settings.appointmentReminders": "تذكيرات المواعيد",
    "settings.appointmentRemindersDesc": "تلقي إشعار قبل المواعيد القادمة",
    "settings.newMessages": "رسائل جديدة",
    "settings.newMessagesDesc": "إشعارات للرسائل الجديدة",
    "settings.alertMatches": "تطابق التنبيهات",
    "settings.alertMatchesDesc": "عندما ينضم محترفون جدد يطابقون تنبيهاتك",
    "settings.reviewNotifs": "إشعارات التقييمات",
    "settings.reviewNotifsDesc": "عندما يقيّم شخص ما خدمتك",
    "settings.account": "الحساب",
    "settings.name": "الاسم",
    "settings.email": "البريد الإلكتروني",
    "settings.role": "الدور",
    "settings.notSet": "غير محدد",

    // Admin
    "admin.title": "لوحة الإدارة",
    "admin.dashboard": "لوحة المعلومات",
    "admin.users": "المستخدمون",
    "admin.ads": "الإعلانات",
    "admin.contacts": "رسائل التواصل",
    "admin.totalUsers": "إجمالي المستخدمين",
    "admin.professionals": "المحترفون",
    "admin.totalBookings": "إجمالي الحجوزات",
    "admin.totalReviews": "إجمالي التقييمات",
    "admin.accessDenied": "تم رفض الوصول: مطلوب صلاحيات المسؤول",
    "admin.updated": "تم التحديث",
    "admin.user": "المستخدم",
    "admin.emailCol": "البريد الإلكتروني",
    "admin.roleCol": "الدور",
    "admin.statusCol": "الحالة",
    "admin.actionsCol": "الإجراءات",
    "admin.locked": "مقفل",
    "admin.active": "نشط",
    "admin.inactive": "غير نشط",
    "admin.pageLabel": "صفحة",
    "admin.adsCount": "إعلان(ات)",
    "admin.newAd": "إعلان جديد",
    "admin.createAd": "إنشاء إعلان",
    "admin.adTitle": "العنوان",
    "admin.adImageUrl": "رابط الصورة",
    "admin.adLinkUrl": "رابط الإعلان (اختياري)",
    "admin.adPosition": "الموضع",
    "admin.homeBanner": "بانر الصفحة الرئيسية",
    "admin.searchBanner": "بانر البحث",
    "admin.sidebar": "الشريط الجانبي",
    "admin.creating": "جاري الإنشاء...",
    "admin.adCreated": "تم إنشاء الإعلان!",
    "admin.adDeleted": "تم حذف الإعلان",
    "admin.noAds": "لا توجد إعلانات بعد",
    "admin.noContacts": "لا توجد رسائل تواصل بعد",

    // Book Appointment
    "book.title": "حجز موعد",
    "book.with": "مع",
    "book.service": "الخدمة",
    "book.selectService": "اختر خدمة",
    "book.generalAppointment": "موعد عام",
    "book.date": "التاريخ",
    "book.time": "الوقت",
    "book.description": "الوصف (اختياري)",
    "book.descriptionPlaceholder": "صف ما تحتاجه...",
    "book.requestAppointment": "طلب موعد",
    "book.requesting": "جاري الطلب...",
    "book.requested": "تم طلب الموعد!",
    "book.requestedTitle": "تم طلب الموعد!",
    "book.requestedDesc": "سيراجع المحترف طلبك ويرد قريباً.",
    "book.viewAppointments": "عرض مواعيدي",
    "book.backToProfile": "العودة للملف الشخصي",
    "book.selectDateTime": "يرجى اختيار التاريخ والوقت",
    "book.back": "رجوع",

    // Footer
    "footer.desc": "ربط العملاء بأفضل المحترفين من خلال تجربة سلسة متعددة القنوات.",
    "footer.platform": "المنصة",
    "footer.findProfessionals": "ابحث عن محترفين",
    "footer.aboutUs": "من نحن",
    "footer.contactUs": "اتصل بنا",
    "footer.forProfessionals": "للمحترفين",
    "footer.createProfile": "إنشاء ملف شخصي",
    "footer.manageBookings": "إدارة الحجوزات",
    "footer.support": "الدعم",
    "footer.helpCenter": "مركز المساعدة",
    "footer.terms": "شروط الخدمة",
    "footer.rights": "جميع الحقوق محفوظة.",

    // Common
    "common.premium": "مميز",
    "common.starred": "نجمة",
    "common.team": "فريق",
    "common.loading": "جاري التحميل...",
    "common.to": "إلى",

    // Profile extras
    "profile.saved": "تم تحديث الملف الشخصي!",
    "profile.saveChanges": "حفظ التغييرات",
    "profile.serviceAdded": "تمت إضافة الخدمة!",
    "profile.serviceRemoved": "تمت إزالة الخدمة",
    "profile.selectCatAndService": "اختر الفئة والخدمة",
    "profile.countryRequired": "البلد مطلوب لكل خدمة",
    "profile.countryPlaceholder": "مثال: لبنان",
    "profile.cityPlaceholder": "مثال: بيروت",
    "profile.workLocation": "موقع العمل",
    "profile.city": "المدينة",
    "profile.category": "الفئة",
    "profile.service": "الخدمة",
    "profile.yearsOfExperience": "سنوات الخبرة",
    "profile.noLocation": "لم يتم تحديد الموقع",
    "profile.noServicesYet": "لا توجد خدمات مسجلة بعد. أضف خدمتك الأولى لبدء تلقي الحجوزات.",
    "profile.to": "إلى",
    "profile.availabilitySaved": "تم حفظ التوفر!",
    "profile.select": "اختر",

    // About extras
    "about.subtitle": "SaySerné هو سوق خدمات مهنية من الجيل القادم مبني على الثقة والشفافية ونهج متعدد القنوات.",
    "about.step1": "تصفح وابحث",
    "about.step2": "احجز وتواصل",
    "about.step3": "قيّم وراجع",

    // Contact extras
    "contact.subtitle": "لديك سؤال أو ملاحظة؟ يسعدنا سماعك.",
    "contact.sentTitle": "تم إرسال الرسالة!",
    "contact.fillAll": "يرجى ملء جميع الحقول",
    "contact.subjectPlaceholder": "ما هو الموضوع؟",
    "contact.messagePlaceholder": "أخبرنا المزيد...",

    // ProfProfile extras
    "profProfile.chatStarted": "بدأت المحادثة! اذهب إلى المحادثات للمتابعة.",

    // Chat media
    "chats.sendImage": "إرسال صورة",
    "chats.sendVideo": "إرسال فيديو",
    "chats.sendLocation": "مشاركة الموقع",
    "chats.shareLocation": "مشاركة الموقع",
    "chats.shareCurrentLocation": "مشاركة الموقع الحالي",
    "chats.or": "أو أدخل يدوياً",
    "chats.locationDescription": "وصف الموقع",
    "chats.locationPlaceholder": "مثال: مكتبي في وسط المدينة",
    "chats.googleMapsLink": "رابط خرائط جوجل",
    "chats.optional": "اختياري",
    "chats.send": "إرسال",
    "chats.location": "الموقع",
    "chats.viewOnMap": "عرض على الخريطة",
    "chats.fileTooLarge": "الملف كبير جداً. الحد الأقصى 5 ميجابايت للصور، 10 ميجابايت للفيديو.",
    "chats.uploading": "جاري الرفع...",
    "chats.locationDenied": "تم رفض الوصول للموقع",
    "chats.locationNotSupported": "تحديد الموقع غير مدعوم",

    // Booking overlap
    "book.selectServiceRequired": "يرجى اختيار خدمة",
    "book.duration": "المدة",
    "book.minutes": "دقيقة",
    "book.hour": "ساعة",
    "book.hours": "ساعات",
    "book.existingAppointments": "المواعيد الموجودة في هذا التاريخ",
    "book.overlapWarning": "تم اكتشاف تعارض في الوقت!",
    "book.overlapDesc": "الوقت المحدد يتعارض مع موعد موجود. يمكنك الإرسال لكن الموافقة غير مرجحة.",
    "book.noServicesAvailable": "لا توجد خدمات متاحة للحجز",

    // Reviews
    "appointments.reviewed": "تم التقييم",

    // Admin extras
    "admin.categories": "الفئات",
    "admin.services": "الخدمات",
    "admin.aboutUs": "من نحن",
    "admin.chatMonitor": "مراقبة المحادثات",
    "admin.fees": "رسوم المحترفين",
    "admin.createUser": "إنشاء مستخدم",
    "admin.viewDetails": "عرض التفاصيل",
    "admin.lock": "قفل",
    "admin.unlock": "فتح القفل",
    "admin.makeAdmin": "تعيين كمسؤول",
    "admin.removeAdmin": "إزالة صلاحية المسؤول",
    "admin.blocked": "محظور",
    "admin.unblocked": "غير محظور",
    "admin.block": "حظر",
    "admin.unblock": "إلغاء الحظر",
    "admin.respond": "رد",
    "admin.reply": "رد",
    "admin.pending": "قيد الانتظار",
    "admin.inProgress": "قيد التنفيذ",
    "admin.closed": "مغلق",
    "admin.allStatuses": "جميع الحالات",
    "admin.save": "حفظ",
    "admin.saving": "جاري الحفظ...",
    "admin.saved": "تم الحفظ!",
    "admin.delete": "حذف",
    "admin.edit": "تعديل",
    "admin.add": "إضافة",
    "admin.name": "الاسم",
    "admin.nameAr": "الاسم (بالعربية)",
    "admin.description": "الوصف",
    "admin.descriptionAr": "الوصف (بالعربية)",
    "admin.status": "الحالة",
    "admin.fee": "الرسوم",
    "admin.feeAmount": "مبلغ الرسوم ($)",
    "admin.feeEnabled": "الرسوم مفعلة",
    "admin.noFees": "لا توجد رسوم محترفين مكونة",
    "admin.userCreated": "تم إنشاء المستخدم!",
    "admin.userUpdated": "تم تحديث المستخدم!",
    "admin.contactReplied": "تم إرسال الرد!",
    "admin.statusChanged": "تم تغيير الحالة!",

    // Profile type
    "profile.profileType": "نوع الملف الشخصي",
    "profile.customer": "عميل",
    "profile.professional": "محترف",
    "profile.profileTypeDesc": "التبديل إلى محترف لإدارة الخدمات والتوفر",

    // Home extra badges/stats
    "home.hero.badge": "سوق الخدمات المهنية",
    "home.stat.countries": "دولة",
    "home.stat.professionals": "محترف",
    "home.stat.satisfaction": "رضا العملاء",
    "home.topRatedBadge": "الأعلى تقييماً",
    "home.categoriesBadge": "استكشف",

    // Missing keys - About
    "about.badge": "من نحن",

    // Missing keys - Contact info cards
    "contact.chatTitle": "تواصل معنا",
    "contact.chatDesc": "نحن هنا للمساعدة في أي أسئلة حول منصتنا.",
    "contact.responseTitle": "استجابة سريعة",
    "contact.responseDesc": "نرد عادة خلال 24 ساعة.",
    "contact.secureTitle": "آمن وخاص",
    "contact.secureDesc": "معلوماتك محفوظة بسرية وأمان.",
    "contact.loggedInAs": "الإرسال باسم",

    // Missing keys - Search
    "search.subtitle": "اكتشف أفضل المحترفين بالقرب منك",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem("sayserne-lang");
    return (stored as Language) || "en";
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("sayserne-lang", newLang);
  }, []);

  const isRTL = lang === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
    if (isRTL) {
      document.body.style.fontFamily = "'Noto Sans Arabic', 'Montserrat', sans-serif";
    } else {
      document.body.style.fontFamily = "";
    }
  }, [lang, isRTL]);

  const t = useCallback((key: string) => {
    return translations[lang][key] || translations["en"][key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
